name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    #actions/checkout@v5.6.2
      - uses: actions/checkout@v3
      - name: Set current date as env variable
        run: echo "MY_DATE=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV

      - name: create test_report
        run: |
           mkdir $GITHUB_WORKSPACE/test_report

      - name: PerfAction for JMeter
  # You may pin to the exact commit or the version.
        uses: QAInsights/PerfAction@v5.6.2
        with:
          # jmeter test plan to execute
          test-plan-path: './CSVSample.jmx'
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          #name: jmeter-results-${{ env.MY_DATE }}
          name: jmeter-results-${{ env.MY_DATE }}
          path: result.jtl

      - name: move jtl files to test_report
        run: |
         mv result.jtl $GITHUB_WORKSPACE/test_report/result.csv

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v3
        with:
         name: test_results-${{ env.MY_DATE }}
         path: test_report

